version: "3.8"
services:
  vex-gateway:
    image: devopsfaith/krakend:2.6
    container_name: vortexcore-be-gateway
    volumes:
      - ".:/etc/krakend"
    ports:
      - "8080:8080"
    networks:
      - vex-network
    command: ["run", "-dc", "krakend.json"]
    restart: always

networks:
  vex-network:
    driver: bridge
